### ISSUE TITLE
Postgres TLS

### ISSUE THREAD

**Issue by loopingrage** [temporalio/helm-charts#148]
**Is your feature request related to a problem? Please describe.**

There doesn't seem to be a way to configure TLS options for Postgres via the helm chart. The underlying server supports it so just seems like it needs to be surfaced in values.

**Describe the solution you'd like**

Ability to configure Postgres TLS options via Temporal Helm Chart.

**Comment by atapio** [comment]
Looks like there actually is a way to configure PostgreSQL TLS by adding `tls.enabled: true` to both SQL persistence configurations:

```yaml
server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "postgres"
          host: _HOST_
          port: 5432
          database: temporal
          user: _USERNAME_
          password: _PASSWORD_
          maxConns: 20
          maxConnLifetime: "1h"
          tls:
            enabled: true
```
