### ISSUE TITLE
[Feature Request] Create keyspaces for BYO Cassandra

### ISSUE THREAD

**Issue by mikhailshilkov** [temporalio/helm-charts#154]
I'm installing this chart with my own Cassandra but I'd still love it to automatically create keyspaces and do all the initialization as if the Cassandra was built-in. The need to build and manually run `temporal-cassandra-tool` disrupts my automation workflow.

**Comment by anderskswanson** [comment]
If Temporalio is not going to support this feature, I would suggest creating a K8s Job to run during cluster setup of your BYO cassandra which does the initialization.

**Comment by robholland** [comment]
The chart will now create the schema for external Cassandra when:

```
cassandra:
  enabled: false
server:
  config:
    persistence:
      default:
        driver: cassandra
```
