### ISSUE TITLE
[Bug] Duplicated entry error when deploy temporal using helm

### ISSUE THREAD

**Issue by eastfisher** [temporalio/helm-charts#204]
**Describe the bug**
Temporal Server start failed.

**To Reproduce**
The configures are provided in Additional context.

**Expected behavior**
Temporal Server successfully start.

**Screenshots/Terminal ouput**
Unable to start server. Error: unable to initialize system namespace: unable to register system namespace: CreateNamespace operation failed. Failed to commit transaction. Error: Error 1062: Duplicate entry '54321-2�hxr@��c��Y�j�' for key 'PRIMARY'

**Versions (please complete the following information where relevant):**
 - OS: Linux
 - Temporal Version v1.9.2
 - Using Helm to deploy Temporal. Helm Version: v1.9.2

**Additional context**

Firstly I initialize the database using `temporal-sql-tool` version v1.9.2.

The Database Version is TiDB v4.0.x.

Several yaml configs are rewritten.

values/values.elasticsearch.yaml

```
elasticsearch:
  enabled: false
  external: true
  host: "xxx"
  port: "xxx"
  version: "v6"
  scheme: "http"
  logLevel: "info"
```

values/values.mysql.yaml

```
server:
  config:
    persistence:
      default:
        driver: "sql"
 
 
        sql:
          driver: "mysql"
          host: xxx
          port: 3306
          database: temporal
          user: root
          password: xxx
          maxConns: 20
          maxConnLifetime: "1h"
 
      visibility:
        driver: "sql"
 
        sql:
          driver: "mysql"
          host: xxx
          port: 3306
          database: temporal_visibility
          user: root
          password: xxx
          maxConns: 20
          maxConnLifetime: "1h"
 
cassandra:
  enabled: false
 
mysql:
  enabled: true
 
postgresql:
  enabled: false
 
schema:
  setup:
    enabled: false
  update:
    enabled: false
```

install cmd:

```
helm install -f values/values.elasticsearch.yaml -f values/values.mysql.yaml temporaltest \
    --set prometheus.enabled=false \
    --set grafana.enabled=false . --timeout 900s
```
