### ISSUE TITLE
[Bug] Setting existingSecret not respected by schema setup/update jobs

### ISSUE THREAD

**Issue by perplexa** [temporalio/helm-charts#261]
### What are you really trying to do?

I am trying to set up temporal using the helm chart on an existing cassandra cluster using the following settings:

```
helm template temporal . \
  --values values/values.cassandra.yaml \
  --set server.config.persistence.default.cassandra.existingSecret=someExistingSecret \
  --set server.config.persistence.visibility.cassandra.password=aPasswordInstead
  --set schema.setup.enabled=true \
  --set schema.update.enabled=true 
```

### Describe the bug

The rendered chart template should include the blocks as follows:

#### default

```
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: someExistingSecret
                  key: password
```

but it has:

```
            - name: CASSANDRA_PASSWORD
              value: password
```

#### visibility

```
            - name: CASSANDRA_PASSWORD
              value: aPasswordInstead
```

This works as expected.

### Minimal Reproduction

See `helm template` command at beginning of issue

### Environment/Versions

- Latest helm chart master branch commit [683c53a](https://github.com/temporalio/helm-charts/tree/683c53afb862c7fd20074eac6d71400134fb08af)
- Helm v3.7.2
