### ISSUE TITLE
[Bug] Jobs do not render create-default-store and create-visibility-store init-containers for externally provided Cassandra

### ISSUE THREAD

**Issue by perplexa** [temporalio/helm-charts#264]
### What are you really trying to do?

I am using the chart to initially set up a Temporal instance on an existing cassandra cluster by setting `cassandra.enabled=false` and `schema.setup.enabled=true`.

### Describe the bug

With both above conditions set, the `schema-setup` job will not create init-containers `create-default-store
` and `create-visibility-store` and subsequently fails with an error: `Keyspace 'temporal' does not exist` during the container run.

Example:

```
      initContainers:
          []
      containers:
        - name: default-schema
```

Expected output should include rendered init-containers:

```
      initContainers:
        - name: create-default-store
          (... truncated)
        - name: create-visibility-store
          (... truncated)
      containers:
        - name: default-schema
```

### Minimal Reproduction

Check out the master branch of this repository and run:

```
helm template temporal . --values values/values.cassandra.yaml --set schema.setup.enabled=true  
```

### Environment/Versions

- Latest helm chart master branch commit [240cc89](https://github.com/temporalio/helm-charts/tree/240cc8909d0da9a26aebab33fb8ef67949b89fa0)
- Helm v3.7.2
