### ISSUE TITLE
[Feature Request] Add the ability to set custom secret key for existing persistence secret

### ISSUE THREAD

**Issue by JoshVee** [temporalio/helm-charts#268]
### Is your feature request related to a problem? Please describe.

The Helm chart currently defaults to a secret key `password` when using an `existingSecret` for persistence credentials.
This does not work in all circumstances, for example the [Bitnami Postgres chart creates a secret](https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/secrets.yaml#L19) with `postgresql-password`.

### Describe the solution you'd like

The chart could provide a dynamic value for the `existingSecretKey` and default to `password` if it's not set.

### Additional context

Example error when using the Bitnami chart:

```
containerStatuses:
    - image: docker.io/temporalio/server:1.14.0
      imageID: ''
      lastState: {}
      name: temporal-worker
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          message: >-
            couldn't find key password in Secret
            default/app-staging-postgres-postgresql
          reason: CreateContainerConfigError
```
