### ISSUE TITLE
Failed to deploy to Kubernetes cluster with hostname

### ISSUE THREAD

**Issue by hongbo-miao** [temporalio/helm-charts#295]
### What are you really trying to do?

I try to deploy Temporal in a Kubernetes cluster with the hostname. However it failed.

### Describe the bug

When I deploy Temporal, I got error for the pod **temporal-cassandra-0**:

> Cassandra: seed provider lists no seeds.

Also, the job **temporal-schema-setup** cannot complete.

Here has more info https://github.com/kubernetes/examples/issues/89

### Minimal Reproduction

Create **west-cluster-config.yaml**

```yaml
apiVersion: k3d.io/v1alpha3
kind: Simple
kubeAPI:
  host: "k8s-hongbomiao.com"
  hostIP: "127.0.0.1"
  hostPort: "6440"
network: hm-network
ports:
  - port: 40000:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --cluster-domain=west.k8s-hongbomiao.com
        nodeFilters:
          - server:*
```

Run

```sh
k3d cluster create west --config=west-cluster-config.yaml
helm install \
    --set server.replicaCount=1 \
    --set cassandra.config.cluster_size=1 \
    --set prometheus.enabled=false \
    --set grafana.enabled=false \
    --set elasticsearch.enabled=false \
    temporaltest . --timeout 15m
```

Then you will see the error in the pod **temporal-cassandra-0**:

> Cassandra: seed provider lists no seeds.

Also, the job **temporal-schema-setup** cannot complete.

### Environment/Versions

- OS and processor: macOS
- Temporal Version: 1.16.2
- Are you using Docker or Kubernetes or building Temporal from source? Kubernetes in k3s

### Additional context

Currently `CASSANDRA_SEEDS` in StatefulSet **temporal-cassandra** is set to

```
temporal-cassandra-0.temporal-cassandra.hm-temporal.svc.cluster.local
```

However, my cluster hostname is `west.k8s-hongbomiao.com`, so correct value is

```
temporal-cassandra-0.temporal-cassandra.hm-temporal.svc.west.k8s-hongbomiao.com
```

If I run

```sh
kubectl patch statefulset temporal-cassandra patch.yaml
```

with **patch.yaml**

```yaml
spec:
  template:
    spec:
      containers:
        - name: temporal-cassandra
          env:
            - name: CASSANDRA_SEEDS
              value: >-
                temporal-cassandra-0.temporal-cassandra.hm-temporal.svc.west.k8s-hongbomiao.com
```

The **temporal-cassandra-0** can be re-deployed successfully.

However, the job **temporal-schema-setup** still fail because of it is using the old `temporal-cassandra-0.temporal-cassandra.hm-temporal.svc.cluster.local`. I am not sure how to update the hostname in the job and restart the job.

It would be great to allow setting CASSANDRA_SEEDS hostname in Helm values. Thanks! 😊
