### ISSUE TITLE
[Bug] Temporal UI not honoring Auth configs

### ISSUE THREAD

**Issue by kkcmadhu** [temporalio/helm-charts#304]
### Web Auth  (outh) config setting breaks

Document says web config can be mounted.  refer https://github.com/temporalio/helm-charts#updating-temporal-web-config 
Recently temporal-web is replaced with tempoal-ui https://github.com/temporalio/helm-charts/commit/098fab57a4c19855b46692aef0df78e2bcf2e336

Looks like temporal-ui is not honoring the  auth configs

### Environment/Versions
1.17

**Comment by nodnallquick** [comment]
Hi I am also having an issue with this, from what I can tell this is because the volumeMount section of the web-deployment.yaml was removed in 1.17.1. Can the docs either be updated to indicated this is no longer supported or the chart updated to mount the volumes again?

**Comment by Igogrek** [comment]
I'm not sure what was the reason for this part to be removed from the chart, but as temp solution ENV vars from here could be used for the ui container https://github.com/temporalio/ui-server/tree/main/docker#quickstart-for-production

i.e. add these to the deployment:
```yaml
    env:
    - name: TEMPORAL_AUTH_ENABLED
      value: "true"
    - name: TEMPORAL_AUTH_PROVIDER_URL
      value: "https://accounts.google.com"
    - name: TEMPORAL_AUTH_CLIENT_ID
      value: "xxxxx-xxxx.apps.googleusercontent.com"
    - name: TEMPORAL_AUTH_CLIENT_SECRET
      value: "xxxxxxxxxxxxxxx"
    - name: TEMPORAL_AUTH_CALLBACK_URL
      value: "https://xxxx.com:8080/auth/sso/callback "
```

**Comment by EslamNasser** [comment]
The issue is still there with the latest helm chart, the config passed in the values files as a volume is not being mounted.

**Comment by drileyst** [comment]
> I'm not sure what was the reason for this part to be removed from the chart, but as temp solution ENV vars from here could be used for the ui container https://github.com/temporalio/ui-server/tree/main/docker#quickstart-for-production
> 
> i.e. add these to the deployment:
> 
> ```yaml
>     env:
>     - name: TEMPORAL_AUTH_ENABLED
>       value: "true"
>     - name: TEMPORAL_AUTH_PROVIDER_URL
>       value: "https://accounts.google.com"
>     - name: TEMPORAL_AUTH_CLIENT_ID
>       value: "xxxxx-xxxx.apps.googleusercontent.com"
>     - name: TEMPORAL_AUTH_CLIENT_SECRET
>       value: "xxxxxxxxxxxxxxx"
>     - name: TEMPORAL_AUTH_CALLBACK_URL
>       value: "https://xxxx.com:8080/auth/sso/callback "
> ```

There's one more value I had to add to get this to work -- TEMPORAL_AUTH_SCOPES. Here's the way I added it to the helm configs.
```yaml
web:
  additionalEnv:
    - name: TEMPORAL_AUTH_ENABLED
      value: "true"
    - name: TEMPORAL_AUTH_PROVIDER_URL
      value: "https://accounts.google.com"
    - name: TEMPORAL_AUTH_CLIENT_ID
      value: "xxxxx-xxxx.apps.googleusercontent.com"
    - name: TEMPORAL_AUTH_CLIENT_SECRET
      value: "xxxxxxxxxxxxxxx"
    - name: TEMPORAL_AUTH_CALLBACK_URL
      value: "https://xxxx.com:8080/auth/sso/callback "
    - name: TEMPORAL_AUTH_SCOPES
      value: "openid,email,profile"
```
