### ISSUE TITLE
[Feature Request] Turn repo to a helm repo

### ISSUE THREAD

**Issue by amirsaber** [temporalio/helm-charts#313]
### Is your feature request related to a problem? Please describe.

We are trying to add this repository as a helm repository for our local development cluster but it's failing to detect repo due to missing index.yaml

```
Failed  25s (x10 over 13m)  source-controller  failed to fetch Helm repository index: failed to cache index to temporary file: failed to fetch https://github.com/temporalio/helm-charts/index.yaml : 404 Not Found  
```

### Describe the solution you'd like

A workflow could be added to this repo to maintain index.yaml as Github pages as described [here](https://helm.sh/docs/howto/chart_releaser_action/#github-actions-workflow)

**Comment by adamstrawson** [comment]
It looks like you're using Flux based on your log (`source-controller`); 

To use a Git Repository, you can use the `GitRepository` kind. 

For example:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: temporal
spec:
  interval: 1m
  url: https://github.com/temporalio/helm-charts
  ref:
    tag: v1.17.1
```
