### ISSUE TITLE
[Bug] Value for service.type is only respected for frontend

### ISSUE THREAD

**Issue by bascht** [temporalio/helm-charts#316]
### What are you really trying to do?

I am trying to enable `NodePort` services for all server components, not only the `frontend`.

### Describe the bug

In the [values.yaml](https://github.com/temporalio/helm-charts/blob/master/values.yaml#L183) all server components look like they're prepared to select a different Service type than the default `ClusterIP`. The final template will only respect the `frontend` though. The restrest is just rendered plain and static: https://github.com/temporalio/helm-charts/blob/master/templates/server-service.yaml#L60

### Minimal Reproduction

Minimal `values.yaml` file to reproduce the issue:

```yaml
---
server:
  frontend:
    service:
      type: NodePort
  history:
    service:
      type: NodePort
  matching:
    service:
      type: NodePort
  worker:
    service:
      type: NodePort
```

### Environment/Versions

- Helm version v3.7.0 on Linux
- Temporal / Chat Version: 1.17.4 

### Additional context

I am not even sure if this is a valid use case, but we are trying to run Temporal across multiple Kubernetes clusters therefore need individual services to be reachable from outside of the cluster.
