### ISSUE TITLE
[Feature Request] Ability to provide DB credentials from a file

### ISSUE THREAD

**Issue by joebowbeer** [temporalio/helm-charts#321]
### Is your feature request related to a problem? Please describe.

How to provide DB credentials to Temporal from a file?

The `existingSecret` method of providing a database password injects the password as an environment variable using valueFrom / secretKeyRef.

However, CIS Benchmark generally recommends not passing secrets as env vars:

> Prefer using secrets as files over secrets as environment variables

### Describe the solution you'd like

Can providing a secret as a file be supported as an option?

### Additional context

[Kubernetes Secret Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/) will mount secrets from external sources as volumes without even creating a secret. This is judged to be even more secure; the fewer Secrets in Kubernetes the better.

In either case, Temporal would be consuming the password from a file instead of from env vars.

**Comment by robholland** [comment]
Temporal itself does not support this so neither will the helm chart. Please open an issue on http://github.com/temporalio/temporal and re-open here if the feature is added.

**Comment by Zeeshan222** [comment]
Any update on this?

**Comment by scjody** [comment]
It's possible to avoid using passwords as environment variables with Temporal as is. The only missing piece is that `temporal-sql-tool` can only read its password from the environment or from the command line, and I've logged https://github.com/temporalio/temporal/issues/10028 about that.

Here's what's needed for this to happen with v1.1.0 of this chart:

1. Disable schema creation via this Helm chart, since it passes the password via the environment:
```yaml
server:
  config:
     persistence:
        datastores:
          default:
            sql:
              createDatabase: false
              manageSchema: false
          visibility:
            sql:
              createDatabase: false
              manageSchema: false
```
2. Create the database and schema via a custom Job. Here's a simplified version (I removed the "if exists" conditionals and update-schema check here for clarity, but they are still needed)
```bash
    PGPASSWORD="$(cat "$SQL_PASSWORD_FILE")"
    echo "${SQL_HOST}:${SQL_PORT}:*:${SQL_USER}:${PGPASSWORD}" > /tmp/.pgpass
    chmod 600 /tmp/.pgpass
    export PGPASSFILE=/tmp/.pgpass
    temporal-sql-tool --password "$PGPASSWORD" create-database
    temporal-sql-tool --password "$PGPASSWORD" setup-schema -v "0.0"
```
3. For Temporal itself, override the config with one created in by initContainer that contains the password directly.
```yaml
  server:
    additionalVolumes:
      - name: tmp
        emptyDir: {}
      - name: temporal-store-password
        secret:
          secretName: temporal-postgresql-admin-password
      - name: processed-config
        emptyDir: {}
    additionalVolumeMounts:
      - name: tmp
        mountPath: /tmp
      - name: processed-config
        mountPath: /etc/temporal/processed-config
        readOnly: true
    additionalEnv:
      - name: TEMPORAL_SERVER_CONFIG_FILE_PATH
        value: /etc/temporal/processed-config/config_template.yaml
    # -- Init container that reads the DB password from a mounted Secret file
    # -- and bakes it into the config template, writing the result to a shared
    # -- emptyDir. Image must be kept in sync with tools.init.image.
    additionalInitContainers:
      - name: prepare-config
        image: [we use a custom image here, but anything with sh and sed should work]
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args:
          - |
            PASSWORD=$(cat /run/secrets/temporal-store-password/password)
            sed \
              -e 's@{{ env "TEMPORAL_DEFAULT_STORE_PASSWORD" | quote }}@"'"$PASSWORD"'"@g' \
              -e 's@{{ env "TEMPORAL_VISIBILITY_STORE_PASSWORD" | quote }}@"'"$PASSWORD"'"@g' \
              /etc/temporal/upstream-config/config_template.yaml \
              > /etc/temporal/processed-config/config_template.yaml
        volumeMounts:
          - name: config
            mountPath: /etc/temporal/upstream-config/config_template.yaml
            subPath: config_template.yaml
            readOnly: true
          - name: temporal-store-password
            mountPath: /run/secrets/temporal-store-password
            readOnly: true
          - name: processed-config
            mountPath: /etc/temporal/processed-config
          - name: tmp
            mountPath: /tmp
```

I'm hoping to work on a PR to this chart to make this cleaner, as well as and https://github.com/temporalio/temporal/issues/10028 when I have the chance. I'll comment here before I start.
