### ISSUE TITLE
[Feature Request] Add Kubernetes job to migrate postgresql schema

### ISSUE THREAD

**Issue by dkravetz** [temporalio/helm-charts#349]
Currently, the helm chart only supports migrating schemas on Cassandra; I would like to add support for the same feature when bringing my own PostgreSQL

### Describe the solution you'd like

Add support for PostgreSQL for the following values in `values.yaml`

```
schema:
  setup:
    enabled: true
  update:
    enabled: true
```
