### ISSUE TITLE
[Feature Request] Being able to configure the web UI

### ISSUE THREAD

**Issue by Smana** [temporalio/helm-charts#369]
Being able to configure the web UI.
Indeed currently the Helm chart supports the creation of a configmap [here](https://github.com/temporalio/helm-charts/blob/master/values.yaml#L256). Unfortunately, this configmap is never used under the `web` deployment.

Actually what I want to do is to configure the OICD `auth`. I found a thread in slack that mention another way than using the configmap: by setting environment variables as follows in the Web deployment:

```yaml
- name: TEMPORAL_AUTH_ENABLED
  value: "true"
- name: TEMPORAL_AUTH_CALLBACK_URL
  value: "https://temporal-dev.xyz.com/"
- name: TEMPORAL_AUTH_PROVIDER_URL
  value: "https://login.microsoftonline.com/XYZ/v2.0"
- name: TEMPORAL_AUTH_LABEL
  value: "azure oidc"
- name: TEMPORAL_AUTH_TYPE
  value: "oidc"
- name: TEMPORAL_AUTH_CLIENT_ID
  value: "XYZ"
- name: TEMPORAL_AUTH_CLIENT_SECRET
  value: "XYZ"
- name: TEMPORAL_AUTH_SCOPES
  value: "openid profile email"
```

This works but declaring environment variables is not supported yet in the Helm chart. Then I noticed [this PR](https://github.com/temporalio/helm-charts/pull/340) but it is not merged since December.

So what is the recommended way of configuring the Web UI please? Are you considering merging the above PR or a solution to make use of the configmap?
