### ISSUE TITLE
[Enhancement] Edit Chart file. Delete redundant value

### ISSUE THREAD

**Issue by devery59** [temporalio/helm-charts#426]
### Is your feature request related to a problem? Please describe.
Helm Chart Suggestion

In Master Branch, cassandra has enable part.
But there is condition, So enable setting is no need required I think...
```
dependencies:
  - name: cassandra
    version: "0.14.3"
    repository: https://charts.helm.sh/incubator
    enabled: false
    condition: cassandra.enabled
``` 

### Describe the solution you'd like
```
dependencies:
  - name: cassandra
    version: "0.14.3"
    repository: https://charts.helm.sh/incubator
    condition: cassandra.enabled
```
