### ISSUE TITLE
Publish temporal helm chart to a helm chart repository (e. g. Helm Hub) 

### ISSUE THREAD

**Issue by markmark206** [temporalio/helm-charts#45]
Please publish Temporal Helm chart to a helm chart repository (such as [Helm Hub](https://hub.helm.sh/charts)), so it is easier to install it.

[Brought to our attention](https://community.temporal.io/t/is-the-helm-chart-published-to-a-helm-repository-somewhere/182?u=markmark) by Kyle, thank you!

**Comment by sagikazarmark** [comment]
Helm hub is not actually a chart repository, and it's being replaced by [Artifact Hub](https://artifacthub.io/)

For simplicity, I'd consider making this repository a helm chart repository using the chart releaser action: https://github.com/helm/chart-releaser-action

**Comment by lerminou** [comment]
Hi @sagikazarmark , any news for this github as chart repo  ?

**Comment by loopingrage** [comment]
Maybe poke the Bitnami folks to take it on?

**Comment by joebowbeer** [comment]
This would be greatly appreciated, and should be easy to resolve.

The simplest approach is to use the `chart-releaser-action`:

https://github.com/helm/chart-releaser-action

This requires a `gh-pages` branch to hold the published charts.

After publishing, the temporalio helm repo can be added via:

`helm repo add temporalio https://temporalio.github.io/helm-charts`

LocalStack publishes their chart here:

https://github.com/localstack/helm-charts/blob/main/.github/workflows/chart-release.yaml

Their helm repo is: https://localstack.github.io/helm-charts

**Comment by sagikazarmark** [comment]
Some other examples:

- https://github.com/sagikazarmark/helm-charts
- https://github.com/dexidp/helm-charts

**Comment by joebowbeer** [comment]
I forked and published from https://github.com/joebowbeer/temporalio-helm-charts

**Comment by loopingrage** [comment]
Ay update here? Seems like a simple thing to do that would save the community a bunch of time and confusion.

**Comment by abatilo** [comment]
Bump. Hard to seriously consider this project until there's an easy way to install this chart

**Comment by hazcod** [comment]
Pinging.

**Comment by ErlanBelekov** [comment]
Any updates on this?

**Comment by hazcod** [comment]
This should be an easy fix so really looking to a quick fix here.

**Comment by franklinkim** [comment]
Some references for anyone else coming along this path:

- #45
- #147 
- #229
- #189
- #42

Looking forward seeing to this progress

**Comment by IkePCampbell** [comment]
Any update on this?

**Comment by arthosdevelops** [comment]
Are there any updates on this?

**Comment by phudtran** [comment]
Having this published would also be very helpful for me as well!

**Comment by gajus** [comment]
Annoying that this is something that would take Temporal team a minute to setup, meanwhile forces everyone else to spend days searching for workarounds.

**Comment by gajus** [comment]
Here is a step by step guide on how to do it:

https://joao.neto.pt/posts/2022/github-helm-registry/

**Comment by thekarpathia** [comment]
Adding another +1 that an officially supported published chart would be nice..!

**Comment by moolitayer** [comment]
+1

**Comment by lerminou** [comment]
The most asked functionality and the simplest 😒

**Comment by ukd1** [comment]
Is this project dead?

**Comment by smartinov** [comment]
Oh lord, it's been years! Is there any way of implementing this? People offered support and examples everywhere!

**Comment by froblesmartin** [comment]
A similar issue exists, it would be better to close one so that there is a single place to comment on the Helm chart publication
https://github.com/temporalio/helm-charts/issues/229

**Comment by vishwa-trulioo** [comment]
If you (Temporal) want people to use their product you must spend bandwidth on action items like this. The fact that it was not addressed for years show how unreliable they are.

**Comment by aisac-clearstreet** [comment]
Hit the same issue. This is my workaround ...
Copy contents of the release you want into a folder and place helmfile outside
with the following contents...

```
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: elastic
    url: https://helm.elastic.co
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: temporal
    namespace: infra-andor
    chart: ./1.20.3
    version: "1.20.3"
    values:
    - "1.20.3/values.yaml"

```
