### ISSUE TITLE
[Bug] Custom env variables for update schema job

### ISSUE THREAD

**Issue by a-porubai** [temporalio/helm-charts#487]
I need to add custom env variables[**SQL_TLS**,**SQL_TLS_DISABLE_HOST_VERIFICATION**] for [update schema job](https://github.com/temporalio/helm-charts/blob/temporal-0.37.0/charts/temporal/templates/server-job.yaml#L91).

How can i add this envs using helm from your official helm repository ?

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dta-temporal
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: qa-infra-temporal
    name: in-cluster
  project: default
  source:
    chart: "temporal"
    repoURL: "https://go.temporal.io/helm-charts/"
    targetRevision: 0.37.0
    helm:
      values: |
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        server:
          config:
            persistence:
              default:
                driver: "sql"
        
                sql:
                  driver: "postgres"
                  host: "postgres-qa-backend-instance.qa-infra-db.svc.cluster.local"
                  port: 5432
                  database: "temporal"
                  tls:
                    enabled: true
                    enableHostVerification: false
        
              visibility:
                driver: "sql"
        
                sql:
                  driver: "postgres"
                  host: "postgres-qa-backend-instance.qa-infra-db.svc.cluster.local"
                  port: 5432
                  database: "temporal_visibility"
                  tls:
                    enabled: true
                    enableHostVerification: false
        elasticsearch:
          enabled: false
        prometheus:
          enabled: false
        grafana:
          enabled: false
        cassandra:
          enabled: false
        mysql:
          enabled: false
    
        **schema:
          setup:
            enabled: true
          update:
            enabled: true**
        
        web:
          ingress:
            enabled: true

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
