### ISSUE TITLE
Helm chart fails to point the correct mysql host  it picks the AWS NAT IP when running on AWS EKS(Kubenetes) in private subnet

### ISSUE THREAD

**Issue by aasimali141290** [temporalio/helm-charts#535]
### What are you really trying to do?

I am trying to run temporal on Kubernetes after creating a database with MySQL tool

### Describe the bug

When workers and other pods come up it points to the wrong host but the correct MySQL user.
gives the following error
```
[Fx] Error returned: received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider
/home/runner/work/docker-builds/docker-builds/temporal/temporal/fx.go:183:
sql schema version compatibility check failed: Error 1045: Access denied for user 'adminSix'@'ec2-44-218-160-171.compute-1.amazonaws.com' (using password: YES)
[Fx] ERROR		Failed to initialize custom logger: could not build arguments for function "go.uber.org/fx".(*module).constructCustomLogger.func2
	/home/runner/go/pkg/mod/go.uber.org/fx@v1.21.1/module.go:292:
failed to build fxevent.Logger:

```
I am using helm chart to install temporal on Kubernetes using the command
`helm install temporaltest temporal \
  --repo https://go.temporal.io/helm-charts \
  -f values.mysql.yaml \
  --set elasticsearch.enabled=false \
  --set server.config.persistence.default.sql.user=user \
  --set server.config.persistence.default.sql.password=user \
  --set server.config.persistence.visibility.sql.user=user \
  --set server.config.persistence.visibility.sql.password=user \
  --set server.config.persistence.default.sql.host=<RDS host > \
  --set server.config.persistence.visibility.sql.host=<RDS host > \
  --timeout 900s  
`
MySQL values file

```
server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "mysql8"
          host: rds-external
          port: 3306
          database: temporal
          user: adminSix
          password: XGbkM1ddz8F6m
          maxConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"

        sql:
          driver: "mysql8"
          host: "rds-external"
          port: 3306
          database: temporal_visibility
          user: adminSeven
          password: XGbkM1ddz8F6m
          maxConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: true

postgresql:
  enabled: false

elasticsearch:
  enabled: false

schema:
  createDatabase:
    enabled: false
  setup:
    enabled: false
  update:
    enabled: false

``` 

### Environment/Versions

- OS and processor: Ubuntu
- Temporal Version: Latest which come from helm repo
- Kubernetes Version: 1.30
