### ISSUE TITLE
[Feature Request] Allow setting authorization via helm values

### ISSUE THREAD

**Issue by qs-synth** [temporalio/helm-charts#540]
### Is your feature request related to a problem? Please describe.

I would like to be able to set the [authorization section](https://github.com/temporalio/temporal/blob/459ad6902d59961a41a5657e9f55ff621805b1d9/docker/config_template.yaml#L256-L268) of `config_template.yaml` from helm values.

### Describe the solution you'd like

It would be simplest if I could pass in an `authorization` block in the same way [tls](https://github.com/temporalio/helm-charts/blob/40acb649b1276cb778e064bf6930aa6facdda344/charts/temporal/values.yaml#L92) is passed in the values file.

### Additional context

In my specific use-case, I would like to enable the default ClaimMapper and Authorizer without needing to rebuild the server image.

```
  config:
    authorization:
      jwtKeyProvider:
        keySourceURIs:
          - http://hostname:port/jwks.json
        refreshInterval: 1m
      permissionsClaimName: permissions
      authorizer: default
      claimMapper: default
```
