### ISSUE TITLE
[Bug] Using values.yml with ArgoCD ApplicationSet not working

### ISSUE THREAD

**Issue by abusutil** [temporalio/helm-charts#548]
### What are you really trying to do?

Hi everyone,

I'm trying to deploy Temporal on my EKS with ArgoCD.
I created a custom chart, that depends the official one, but any of my values are applied.

Temporal tried to be deployed with the default values are inside your `values.yaml` file. It doesn't overwrite it with mine.

So, in my `values.yaml`, those components are set to `enabled: false`, but are created anyway.

#### My chart.yml
```
---
apiVersion: v2
name: temporal
description: Helm chart to deploy Temporal
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: temporal
    repository: https://go.temporal.io/helm-charts
    version: v0.44.0
```

#### values.yml
```
secret:
  secretName: temporal-secret #custom value for external-secret
server:
  config:
    persistence:
      default:
        driver: postgres
        sql:
          port: 5432
          user: temporal
          existingSecret: temporal-secret
          secretName: db_admin_password
      visibility:
        driver: postgres
        sql:
          port: 5432
          user: temporal
          existingSecret: temporal-secret
          secretName: db_admin_password
elasticsearch:
  enabled: false
prometheus:
  enabled: false
grafana: 
  enabled: false
cassandra:
  enabled: false
```

#### values-environment.yml
```
server:
  replicaCount: 1
  config:
    persistence:
      default:
        sql:
          host: my.db.environment.com
      visibility:
        sql:
          host: my.db.environment.com
web:
  enabled: true
  ingress:
    enabled: false
```

#### ArgoCD ApplicationSet
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: temporal
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/my-repo.git
              revision: main
              files:
                - path: "charts/temporal/values.yaml"
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster

  template:
    metadata:
      name: 'temporal-{{metadata.labels.environment}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: temporal
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: https://github.com/my-repo.git
          targetRevision: main
          path: '{{path}}'
          helm:
            valueFiles:
              - values.yaml
              - values-{{metadata.labels.environment}}.yaml
      destination:
        server: '{{server}}'
        namespace: temporal
```

![Screenshot 2024-08-16 at 10 00 24](https://github.com/user-attachments/assets/9feb130b-3c4c-4eb2-9a15-d65b0372f4a8)

The configmap doesn't use my custom values from `values.yaml`
<img width="872" alt="Screenshot 2024-08-16 at 19 30 24" src="https://github.com/user-attachments/assets/bd1d2e94-499e-4b87-ac89-3c2509556e55">

Values are taken into account in ArgoCD application
<img width="621" alt="Screenshot 2024-08-20 at 17 29 52" src="https://github.com/user-attachments/assets/473b873a-9668-4f40-99b3-9a5580d95b76">

I don't understand this weird behavior. I missing something ?

Thanks in advance for your advices.

**Comment by abusutil** [comment]
I solved my issue by adding condition to the chart.

**Chart.yml**
```
dependencies:
  - condition: temporal-sandbox.enabled
    name: temporal
    alias: temporal-sandbox
    repository: https://temporalio.github.io/helm-charts
    version: 0.44.0
```

**Values.yml**
```
temporal-sandbox:
  serviceAccount:
    create: true
    name: temporal-sa
    ...
```
