### ISSUE TITLE
[Bug] Custom Resource Labels seems to be broken after 0.45.0

### ISSUE THREAD

**Issue by VLZZZ** [temporalio/helm-charts#575]
### What are you really trying to do?

Hi there!

I'm experiencing issues after #539 was introduced in `0.45.0`

### Describe the bug

Additional custom PodLabels being merged to the previous line (at least for `web` and `admintools` in my case)

We have custom PodLabel set like this in values.yaml
```
admintools:
    podLabels:
      grafana.xxx.com/component-type: infra
```

Which resulted in (output of `helm template` command)
```
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admintools
        app.kubernetes.io/name: temporal
        helm.sh/chart: temporal-0.45.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.25.0"
        app.kubernetes.io/part-of: temporalgrafana.xxx.com/component-type: 
infra
```

and corresponding mapping error:
```
 error converting YAML to JSON: yaml: line 29: mapping values are not allowed in this context
```

### Environment/Versions

- Temporal Version: temporaHelm-chart version `0.44.0`
- Kubernetes
