### ISSUE TITLE
[Bug] Pod annotations serialized without qoutes

### ISSUE THREAD

**Issue by slavb18** [temporalio/helm-charts#595]
### What are you really trying to do?

I want to setup pod annotations using values.yaml for step-ca 

### Describe the bug
Example values.yaml:
```yaml
schema:
  podAnnotations:
    autocert.step.sm/mode: "0600"
server:
  podAnnotations:
    autocert.step.sm/mode: "0600"
```

In Job I see right result with quotes **"0600"**
```yaml
      annotations:
        autocert.step.sm/mode: "0600"
```

In Deployment created from temporal/templates/server-deployment.yaml result is wrong: 

```yaml
      annotations:
         autocert.step.sm/mode: 0600
```
  
### Minimal Reproduction

run  `helm install --namespace temporal --dry-run  --repo https://go.temporal.io/helm-charts -f values.yaml temporal temporal --timeout 900s --create-namespace`

### Environment/Versions

- OS and processor: Linux
- Temporal Version: 1.25.1 / helm chart 0.50.0  

I think bug in temporal.resourceAnnotations, and Job template working correct becouse it not uses temporal.resourceAnnotations
