### ISSUE TITLE
[Bug] temporal services (non headless) does not declare 9090 metrics port.

### ISSUE THREAD

**Issue by esn89** [temporalio/helm-charts#597]
### What are you really trying to do?
I am trying to get metrics sent to our Prometehus

### Describe the bug

Deploying via the helm chart, I find that our temporal services such as  `temporal-frontend` does not declare the metrics 9090 port:

```yaml
  ports:
  - name: grpc-rpc
    port: 7233
    protocol: TCP
    targetPort: rpc
  - name: http
    port: 7243
    protocol: TCP
    targetPort: http
```

As a result I am not getting any metrics from the ServiceMonitors which I enabled in your helm chart.

### Minimal Reproduction

These are the parameters I have passed in, into the helm chart via ArgoCD:

```yaml
      - name: (index .Values.web.additionalEnv 0).name
        value: 'TEMPORAL_START_WORKFLOW_DISABLED'
      - name: (index .Values.web.additionalEnv 0).value
        value: 'false'
      - name: server.metrics.serviceMonitor.enabled
        value: 'true'
      - name: server.frontend.metrics.serviceMonitor.enabled
        value: 'true'
      - name: prometheus.enabled
        value: 'false'
```

I do see that the svc `temporal-frontend-headless` has the 9090, how come the `temporal-frontend` does not?
Our deployment uses `temporal-frontend` service on the 7233 for workflows.

### Environment/Versions

- OS and processor: Running on GKE 1.30
- Helm Chart 0.50.0, Application version 1.25.1
