### ISSUE TITLE
[Bug] Elastic TLS

### ISSUE THREAD

**Issue by freddierice** [temporalio/helm-charts#606]
### What are you really trying to do?
Connect to Elasticsearch with a TLS configuration.

### Describe the bug

Elasticsearch TLS config is not passed in.

### Minimal Reproduction
TLS is not included if I have this config.
```
elasticsearch:
    enabled: false
    external: true
    host: myhost.name.cluster
    port: "9200"
    version: v7
    scheme: https
    logLevel: error
    username: anyusername
    password: anypassword
    tls:
        caData: thecadata
        certData: thecertdata
        keyData: thekeydata
        enableHostVerification: false
        enabled: true
```

### Environment/Versions
n/a

### Additional context
n/a
