### ISSUE TITLE
[Bug] service config does not overwrite server config

### ISSUE THREAD

**Issue by Dariusch** [temporalio/helm-charts#608]
### What are you really trying to do?

Service-specified configuration is not overwritten

### Describe the bug

According to the values.yaml in https://github.com/temporalio/helm-charts/blob/main/charts/temporal/values.yaml#L26-L27 The e.g. `web.replicaCount` should overwrite the `server.replicaCount` but it does not.

```yaml
  # Global default settings (can be overridden per service)
  replicaCount: 1
```

### Minimal Reproduction
```yaml
server:
  enabled: true
  replicaCount: 1

frontend:
  replicaCount: 3
```

```shell
helm template -f temporal.yaml temporal/temporal  | grep replicas
  replicas: 1
  replicas: 1
  replicas: 1
  replicas: 1
  replicas: 1
  replicas: 1
```

Replicas is only one example. E.g. resources are also not working

**Comment by robholland** [comment]
Your value are not set correctly (mis-scoped). They should be:

```
server:
  replicaCount: 1
  frontend:
    replicaCount: 2
```

That sets the replica counts as documented.

`web` is not counted as a service in the same way and does not inherit the default from the `server.replicaCount` setting, but setting `web.replicaCount` does set the value in the template.
