### ISSUE TITLE
[Bug] Enable SSO with GitHub OAuth App in Web UI

### ISSUE THREAD

**Issue by baduker** [temporalio/helm-charts#612]
### What are you really trying to do?

I've been trying to enable SSO in temporal web ui using an OAuth app created in GitHub.

### Describe the bug

I have temporal deployed via the official helm chart (version 0.51.0).

I’m trying to enable SSO via GitHub OAuth App in the web UI.

Here’s the relevant part of my `values.yaml`

```yaml
web:
  ingress:
    enabled: true
    className: alb
    hosts:
      - temporal.MY-DOMAIN.click
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: "HTTP"
      alb.ingress.kubernetes.io/group.name: MY-GROUP
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/target-type: ip
      external-dns.alpha.kubernetes.io/manage: "true"
  additionalEnv:
    - name: TEMPORAL_AUTH_ENABLED
      value: "true"
    - name: TEMPORAL_AUTH_PROVIDER_URL
      value: "https://github.com/login/oauth/authorize"
    - name: TEMPORAL_AUTH_CLIENT_ID
      value: "Ov23lDEADCODE8LHILl"
    - name: TEMPORAL_AUTH_CALLBACK_URL
      value: "https://temporal.MY-DOMAIN.click/auth/sso/callback"
  additionalEnvSecretName: temporal-auth-client-secret
  ```
  
  The moment I deploy this, the `web-ui` pod dies. I'm sure the envs get passed along with the `temporal-auth-client-secret` because when I inspect the pod I see this:
  
  ```yaml
  Restart Count:  5
Environment Variables from:
 temporal-auth-client-secret  Secret  Optional: false                 
Environment:                                            
 TEMPORAL_ADDRESS:            temporal-dev-frontend.temporal.svc:7233     
 TEMPORAL_AUTH_ENABLED:       true        
 TEMPORAL_AUTH_PROVIDER_URL:  https://github.com/login/oauth/authorize               
 TEMPORAL_AUTH_CLIENT_ID:     Ov23lDEADCODE8LHILl
 TEMPORAL_AUTH_CALLBACK_URL:  https://temporal.<MY_DOMAIN>.click/auth/sso/callback
 ```
 
 When I check the logs, I get a huge HTML from GitHub that when rendered says it's a `404`.
 
 This is the log starts with:
 
 ```text
 2024/12/04 16:00:25 Loading config; env=docker,configDir=config
2024/12/04 16:00:25 Loading config files=[config/docker.yaml]
2024/12/04 16:00:25 Loading config; env=docker,configDir=config
2024/12/04 16:00:25 Loading config files=[config/docker.yaml]
2024/12/04 16:00:26 404 Not Found:

<GITHUB'S 404 HTML GOES HERE>
```

When I go to https://github.com/login/oauth/authorize?client_id=Ov23lDEADCODE8LHILl in my brwoser I get this screen:

![Screenshot 2024-12-04 at 17 24 37](https://github.com/user-attachments/assets/b8b25304-2795-4669-bbdd-a223823aa2b4)

How do I make the SSO work with GitHub OAuth app?

### Environment/Versions

- Temporal Version: Helm Chart v0.51.0 and Temporal Web `2.31.2`
- I'm using Kubernetes
