### ISSUE TITLE
[Feature Request] Allow setting securityContext for check-elasticsearch-index initContainer

### ISSUE THREAD

**Issue by geckiss** [temporalio/helm-charts#662]
### Is your feature request related to a problem? Please describe.

We are unable to deploy Temporal with Elasticsearch configured as visibility store due to container securityContext not being set for check-elasticsearch-index initContainer. The problem occurs for frontend, history, matching and worker Deployments with following error:

`Pods "temporalio-testing-frontend-6b95f7886d-l8hrp" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "check-elasticsearch-index" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "check-elasticsearch-index" must set securityContext.capabilities.drop=["ALL"]):Deployment does not have minimum availability.`

The template does not provide an option to set securityContext:

```yaml
{{- if or $.Values.elasticsearch.enabled $.Values.elasticsearch.external }}
        - name: check-elasticsearch-index
          image: "{{ $.Values.admintools.image.repository }}:{{ $.Values.admintools.image.tag }}"
          imagePullPolicy: {{ $.Values.admintools.image.pullPolicy }}
          command: ['sh', '-c', 'until curl --silent --fail --user "$ES_USER:$ES_PWD" $ES_SCHEME://$ES_HOST:$ES_PORT/$ES_VISIBILITY_INDEX 2>&1 > /dev/null; do echo waiting for elasticsearch index to become ready; sleep 1; done;']
          env:
            {{- include "temporal.admintools-env" (list $ "visibility") | nindent 12 }}
{{- end }}
```

### Describe the solution you'd like

We are already able to set containerSecurity context for frontend, history, matching and worker components, for example [here](https://github.com/temporalio/helm-charts/blob/7832ae79fcb5f781b70eaedf01546b629272c408/charts/temporal/values.yaml#L244). It can be further added to this/those initContainer/s which would be correctly templated for each corresponding service through $serviceValues.

```yaml
{{- if or $.Values.elasticsearch.enabled $.Values.elasticsearch.external }}
        - name: check-elasticsearch-index
          image: "{{ $.Values.admintools.image.repository }}:{{ $.Values.admintools.image.tag }}"
          imagePullPolicy: {{ $.Values.admintools.image.pullPolicy }}
          command: ['sh', '-c', 'until curl --silent --fail --user "$ES_USER:$ES_PWD" $ES_SCHEME://$ES_HOST:$ES_PORT/$ES_VISIBILITY_INDEX 2>&1 > /dev/null; do echo waiting for elasticsearch index to become ready; sleep 1; done;']
          env:
            {{- include "temporal.admintools-env" (list $ "visibility") | nindent 12 }}
          {{- with $serviceValues.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
```
