### ISSUE TITLE
[Bug] resources not properly applied to create-{{ store }}-store schema job initContainers.

### ISSUE THREAD

**Issue by abarganier** [temporalio/helm-charts#668]
### What are you really trying to do?

A company policy is that all of our container definitions require resource requests/limits set, so I am attempting to set `resources` on all containers deployed via the helm chart.

### Describe the bug

The create-{{ store }}-store [init container](https://github.com/temporalio/helm-charts/blob/e8ae865d87b35240dcc25f55be5ed97ebb061c03/charts/temporal/templates/server-job.yaml#L52-L72) doesn't use the CPU/memory [resources set in the values file](https://github.com/temporalio/helm-charts/blob/e8ae865d87b35240dcc25f55be5ed97ebb061c03/charts/temporal/values.yaml#L445). 
Seems like all the other init containers used in the schema job [respect the resources set](https://github.com/temporalio/helm-charts/blob/e8ae865d87b35240dcc25f55be5ed97ebb061c03/charts/temporal/templates/server-job.yaml#L94).

The resources should be imposed on all containers targeted by the `schema` values.

### Minimal Reproduction

For example, if I set values to:
```yaml
  schema:
    createDatabase:
      enabled: true
    setup:
      enabled: true
    update:
      enabled: true
    resources:
      limits:
        cpu: 4
        memory: 4Gi
      requests:
        cpu: 4
        memory: 4Gi
```

It generates:
```yaml
        - name: create-default-store
          image: "xxxx"
          imagePullPolicy: IfNotPresent
          command: ['temporal-sql-tool', 'create-database']
          env:
            - name: SQL_PLUGIN
              value: postgres12
            - name: SQL_HOST
              value: temporal-proto-pg-postgresql.default.svc.cluster.local
            - name: SQL_PORT
              value: "5432"
            - name: SQL_DATABASE
              value: temporal
            - name: SQL_USER
              value: temporal
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: foobar-dev-temporal-default-store
                  key: password
        - name: create-visibility-store
          image: "xxxx"
          imagePullPolicy: IfNotPresent
          command: ['temporal-sql-tool', 'create-database']
          env:
            - name: SQL_PLUGIN
              value: postgres12
            - name: SQL_HOST
              value: temporal-proto-pg-postgresql.default.svc.cluster.local
            - name: SQL_PORT
              value: "5432"
            - name: SQL_DATABASE
              value: temporal_visibility
            - name: SQL_USER
              value: postgres
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: foobar-dev-temporal-visibility-store
                  key: password
        - name: setup-default-store
          ...
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
        - name: setup-visibility-store
          ...
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
        - name: update-default-store
          ...
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
        - name: update-visibility-store
          ...
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
      containers:
        - name: done
          image: "xxxx"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo "Store setup completed"']
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
```

Note the lack of resources defined on the first 2 initContainers

### Environment/Versions

Chart version: `0.57.0`
