### ISSUE TITLE
[Bug] Error retrieving settings when using internal-frontend

### ISSUE THREAD

**Issue by vitornp** [temporalio/helm-charts#682]
### What are you really trying to do?

I'm adding new labels to the internal-frontend deployment

### Describe the bug

None of the customization options can be set in the internal-frontend service.

### Minimal Reproduction

Commad:
```bash
helm install \
    --repo https://go.temporal.io/helm-charts \
    -f values.yaml \
    temporaltest temporal \
    --timeout 900s
```

values.yaml

```yaml
server:
  internalFrontend:
    enabled: true
    podAnnotations:
      app: temporal-internal-frontend
    podLabels:
      app: temporal-internal-frontend
    deploymentAnnotations:
      app: temporal-internal-frontend
    deploymentLabels:
      app: temporal-internal-frontend
```

To get around the problem it was necessary

```yaml
server:
  internalFrontend:
    enabled: true
  internal-frontend:
    podAnnotations:
      app: temporal-internal-frontend
    podLabels:
      app: temporal-internal-frontend
    deploymentAnnotations:
      app: temporal-internal-frontend
    deploymentLabels:
      app: temporal-internal-frontend
```

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?
