### ISSUE TITLE
[Bug] Schema Job failed to create namespace

### ISSUE THREAD

**Issue by msolimans** [temporalio/helm-charts#698]
### What are you really trying to do?

I tried to install temporal with helm chart values and I turned on namespace's creation to `true` but schema job in init container `create-x-namespace` 

### Describe the bug

running 
here is the code snippet from values.yml I used

```
server:
  config:
    namespaces:
      create: true
      namespace: 
        - name: temporalx 
          retention: 3d
```

schema pod crashed in creating namespace - here are the logs

```
kubectl logs -n temporal releease-name-temporal-scehma.... -c create-temporalx-namespace

Error: provide either namespace-id flag or namespace as an argument. Global flag 'namespace' is not supported by namespace commands

```

### Minimal Reproduction

use `helm template` to generate manifests and apply them.
- helm repo add temporal ...
- helm repo update 
- helm template .. > temporal.yml 

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?
